import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import { AppWrapper } from "@/helpers/store";
import Footer from "./ui/footer";
import Providers from "./providers";
import Preheader from "./ui/preheader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({ subsets: ["latin"] });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RUKS Á LA MODE",
  description: "Generated by create next app",
  icons: {
    icon: "/RALMICON.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased bg-[#f5f5f5]`}>
        <AppWrapper>
          <div className="">
            <Preheader />
            <Header />
            <Providers>{children}</Providers>
            <Footer />
          </div>
        </AppWrapper>
      </body>
    </html>
  );
}
